<?php

use \Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_cron().
 */
function dubai_expo_2020_general_cron() {

  $before = new DrupalDateTime('-7 days');

  $results = \Drupal::entityQuery('node')
                    ->condition('status', 1)
                    ->condition('type', 'news')
                    ->condition('field_is_twitter_feed', TRUE, '=')
                    ->condition('field_media_date', $before->format(\Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface::DATETIME_STORAGE_FORMAT), '<')
                    ->addTag('distinct')
                    ->execute();

  if (!empty($results)) {
    foreach ($results as $nid) {
      $node = \Drupal\node\Entity\Node::load($nid);
      $node->setUnpublished();
      $node->save();
    }
  }
}
